import type { Place } from './types';

export const places: Place[] = [
  // Uganda
  {
    id: 'ug-1',
    name: 'Bwindi Impenetrable National Park',
    country: 'Uganda',
    type: 'Attraction',
    description: 'Home to nearly half of the world\'s mountain gorillas.',
    longDescription: 'Bwindi Impenetrable National Park is a UNESCO World Heritage site in southwestern Uganda. It is renowned for its exceptional biodiversity, with more than 160 species of trees and over 120 species of mammals. Its main attraction is the gorilla tracking, offering a once-in-a-lifetime opportunity to see these magnificent creatures up close.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.087, lng: 29.619 },
    contact: { phone: '+256-414-346287', website: 'https://www.ugandawildlife.org' },
    rating: 4.9,
  },
  {
    id: 'ug-2',
    name: 'Serena Hotel Kampala',
    country: 'Uganda',
    type: 'Hotel',
    description: 'A 5-star hotel offering a world-class experience in Kampala.',
    longDescription: 'Nestled in the heart of Kampala, the Serena Hotel stands amidst 17 acres of beautifully manicured water gardens. The hotel features an international conference center, a roof-top terrace, and a rock-hewn pool. It provides a tranquil and secure environment for both business and leisure travelers.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: 0.316, lng: 32.589 },
    contact: { phone: '+256-312-309000', website: 'https://www.serenahotels.com' },
    rating: 4.6,
  },
  {
    id: 'ug-3',
    name: 'The Lawns',
    country: 'Uganda',
    type: 'Restaurant',
    description: 'A unique dining experience with a specialty in game meat.',
    longDescription: 'The Lawns offers a serene dining environment with lush gardens and a sophisticated ambiance. The menu is a fusion of international cuisine with a special focus on game meats like crocodile, ostrich, and gnu. It\'s a perfect spot for a romantic dinner or a special celebration.',
    images: ['https://placehold.co/800x600.png'],
    location: { lat: 0.301, lng: 32.587 },
    contact: { phone: '+256-772-200002', website: 'https://thelawns.co.ug' },
    rating: 4.5,
  },
  {
    id: 'ug-4',
    name: 'Bwindi Impenetrable Forest',
    country: 'Uganda',
    type: 'Attraction',
    description: 'Home to nearly half of the world\'s remaining mountain gorillas, making it one of the top destinations for gorilla trekking.',
    longDescription: 'Bwindi Impenetrable Forest is one of Uganda’s most famous natural treasures, located in southwestern Uganda along the border with the Democratic Republic of Congo. It covers about 331 square kilometers of dense tropical rainforest and is recognized as a UNESCO World Heritage Site. It is home to nearly half of the world’s remaining mountain gorillas, making it one of the top destinations for gorilla trekking. The forest hosts over 120 mammal species, including chimpanzees, elephants, forest buffalo, and various monkeys, as well as more than 350 bird species. Its dense vegetation, steep terrain, and rich plant life make it one of the most biologically diverse forests in Africa.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.087, lng: 29.619 },
    contact: { phone: '+256-414-346287', website: 'https://www.ugandawildlife.org' },
    rating: 4.9,
  },
  {
    id: 'ug-5',
    name: 'Murchison Falls National Park',
    country: 'Uganda',
    type: 'Attraction',
    description: 'Uganda’s largest and oldest national park, famous for the spectacular Murchison Falls where the Nile River squeezes through a narrow gorge.',
    longDescription: 'Murchison Falls National Park is Uganda’s largest and oldest national park, covering about 3,840 square kilometers in the northwest. It’s famous for the spectacular Murchison Falls, where the Nile River squeezes through a narrow gorge and plunges over 40 meters down. The park hosts diverse animals including elephants, lions, leopards, giraffes, buffalo, hippos, crocodiles, and many bird species. A popular way to experience the park is by boat along the Nile, cruising to the base of the falls.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: 2.273, lng: 31.792 },
    contact: { phone: 'N/A', website: 'https://www.ugandawildlife.org' },
    rating: 4.8,
  },
  {
    id: 'ug-6',
    name: 'Uganda Wildlife Conservation Education Centre',
    country: 'Uganda',
    type: 'Attraction',
    description: 'A leading conservation education facility, home to rescued and rehabilitated wildlife in habitats mimicking their natural environments.',
    longDescription: 'Established in 1952, UWEC has grown into Uganda’s leading conservation education facility, focusing on wildlife rescue, rehabilitation, and breeding endangered species. It is home to over 250 animals representing more than 120 species. The center features four main habitats designed to mimic natural environments: savannah, forest, wetland, and open water. Education is central to UWEC’s mission, offering guided tours and interactive exhibits to raise awareness about wildlife conservation.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: 0.056, lng: 32.463 },
    contact: { phone: 'N/A', website: 'https://uwec.ug' },
    rating: 4.6,
  },
  {
    id: 'ug-7',
    name: 'Entebbe Botanical Gardens',
    country: 'Uganda',
    type: 'Attraction',
    description: 'Historic gardens on the shores of Lake Victoria, showcasing over 500 indigenous and exotic plant species.',
    longDescription: 'Established in 1898, the Entebbe Botanical Gardens cover about 40.7 hectares and serve as a center for plant conservation, education, and recreation. The gardens house over 500 plant species, including medicinal plants, tropical rainforest trees, and a palm tree avenue. It\'s also home to various primate species and over 150 recorded bird species, making it ideal for nature walks, bird watching, and picnicking.',
    images: ['https://placehold.co/800x600.png'],
    location: { lat: 0.065, lng: 32.476 },
    contact: { phone: 'N/A', website: 'N/A' },
    rating: 4.5,
  },
  {
    id: 'ug-8',
    name: 'Ngamba Island Chimpanzee Sanctuary',
    country: 'Uganda',
    type: 'Attraction',
    description: 'A safe haven for orphaned eastern chimpanzees, providing a semi-natural forest environment for them to thrive.',
    longDescription: 'Ngamba Island Chimpanzee Sanctuary is a safe haven for orphaned eastern chimpanzees rescued from poachers. It covers about 100 acres of forest on Ngamba Island, providing a semi-natural environment for over 50 chimpanzees. Visitors can observe chimpanzee feeding sessions from a raised viewing platform and learn about conservation work. Overnight stays are available at the Ngamba Eco-Lodge.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -0.103, lng: 32.650 },
    contact: { phone: 'N/A', website: 'https://ngambaisland.org' },
    rating: 4.8,
  },
  {
    id: 'ug-9',
    name: 'Gaddafi National Mosque',
    country: 'Uganda',
    type: 'Attraction',
    description: 'The largest mosque in East Africa, offering panoramic views of Kampala from its minaret.',
    longDescription: 'The Uganda National Mosque, formerly known as the Gaddafi National Mosque, is located atop Old Kampala Hill and is the largest mosque in East Africa. Completed in 2006, it can accommodate up to 15,000 worshippers. Its design blends Islamic and Ugandan cultural elements, featuring a large dome and a 50.5-meter minaret. Visitors can climb the 272 steps of the minaret for stunning panoramic views of Kampala.',
    images: ['https://placehold.co/800x600.png'],
    location: { lat: 0.318, lng: 32.571 },
    contact: { phone: 'N/A', website: 'N/A' },
    rating: 4.6,
  },
  {
    id: 'ug-10',
    name: 'Mabamba Swamp',
    country: 'Uganda',
    type: 'Attraction',
    description: 'A vast wetland renowned as one of the best places in Uganda to see the elusive and prehistoric-looking Shoebill stork.',
    longDescription: 'Mabamba Swamp, located west of Entebbe, is known for its rich biodiversity and is one of the best places in Uganda to see the elusive Shoebill stork in the wild. This wetland covers over 16,500 hectares and features dense papyrus vegetation. Besides the Shoebill, Mabamba Swamp is home to over 300 bird species, including the Papyrus Gonolek and African Fish Eagle. The best time to visit is in the early morning.',
    images: ['https://placehold.co/800x600.png'],
    location: { lat: 0.076, lng: 32.348 },
    contact: { phone: 'N/A', website: 'N/A' },
    rating: 4.7,
  },
  {
    id: 'ug-11',
    name: 'Kazinga Channel',
    country: 'Uganda',
    type: 'Attraction',
    description: 'A natural waterway in Queen Elizabeth National Park with one of the largest concentrations of hippos in the world.',
    longDescription: 'Kazinga Channel is a 32-kilometer natural waterway connecting Lake Edward to Lake George in Queen Elizabeth National Park. It is known for its rich biodiversity and is a top spot for wildlife lovers. The channel has one of the largest concentrations of hippos in the world and is home to many Nile crocodiles. Boat cruises on the channel offer excellent chances to see wildlife up close, including elephants and buffalo on the banks.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -0.198, lng: 29.932 },
    contact: { phone: 'N/A', website: 'https://www.ugandawildlife.org' },
    rating: 4.8,
  },
  // Kenya
  {
    id: 'ke-1',
    name: 'Maasai Mara National Reserve',
    country: 'Kenya',
    type: 'Attraction',
    description: 'Famous for the Great Migration of wildebeest and zebra.',
    longDescription: 'The Maasai Mara is one of the most famous and important wildlife conservation and wilderness areas in Africa, world-renowned for its exceptional populations of lion, leopard, cheetah and African bush elephant. It also hosts the Great Migration, which secured it as one of the Seven Natural Wonders of Africa, and as one of the ten Wonders of the World.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.683, lng: 35.250 },
    contact: { phone: '+254-20-600800', website: 'https://www.kws.go.ke' },
    rating: 4.8,
  },
  {
    id: 'ke-2',
    name: 'Giraffe Manor',
    country: 'Kenya',
    type: 'Hotel',
    description: 'An exclusive boutique hotel, famous for its resident Rothschild giraffes.',
    longDescription: 'Giraffe Manor is set in 12 acres of private land within 140 acres of indigenous forest in the Langata suburb of Nairobi. As one of Nairobi\'s most iconic buildings, Giraffe Manor has extraordinary appeal, that harks back to the 1930s when European visitors first flocked to East Africa to enjoy safaris. With its stately façade, elegant interior, verdant green gardens, sunny terraces and delightful courtyards, guests often remark that it’s like walking into the film Out of Africa: indeed, one of its twelve rooms is named after the author Karen Blixen.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.369, lng: 36.745 },
    contact: { phone: '+254-20-5020888', website: 'https://www.thesafaricollection.com' },
    rating: 4.9,
  },
  {
    id: 'ke-3',
    name: 'Carnivore Kenya',
    country: 'Kenya',
    type: 'Restaurant',
    description: 'An open-air restaurant famous for its nyama choma (roasted meat).',
    longDescription: 'Carnivore is a unique dining experience. The restaurant\'s specialty is meat, and features an all-you-can-eat meat buffet. They serve a wide variety of meat, including game meat, roasted on traditional Maasai swords over a huge charcoal pit that dominates the entrance of the restaurant. It is a must-visit for any meat lover visiting Nairobi.',
    images: ['https://placehold.co/800x600.png'],
    location: { lat: -1.321, lng: 36.800 },
    contact: { phone: '+254-733-611604', website: 'https://tamarind.co.ke/carnivore' },
    rating: 4.7,
  },
  // Tanzania
  {
    id: 'tz-1',
    name: 'Serengeti National Park',
    country: 'Tanzania',
    type: 'Attraction',
    description: 'A vast ecosystem famous for its massive annual migration of wildebeest and zebra.',
    longDescription: 'The Serengeti National Park is a Tanzanian national park in the Serengeti ecosystem in the Mara and Simiyu regions. It is famous for its annual migration of over 1.5 million white-bearded (or brindled) wildebeest and 250,000 zebra and for its numerous Nile crocodile and honey badger.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -2.333, lng: 34.833 },
    contact: { phone: '+255-27-250-3471', website: 'https://www.tanzaniaparks.go.tz' },
    rating: 4.9,
  },
  {
    id: 'tz-2',
    name: 'The Highlands',
    country: 'Tanzania',
    type: 'Hotel',
    description: 'A unique high-altitude camp on the slopes of the Olmoti volcano.',
    longDescription: 'Set on the edge of the mountain forest hugging the Olmoti volcano to the north of Ngorongoro Crater, The Highlands has sweeping views right across the Serengeti. The eight canvas-and-glass domed suites are a clever blend of cutting-edge design and traditional Maasai-inspired furnishings. It offers a range of activities, from crater floor game drives to community and cultural visits and hiking.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -2.859, lng: 35.534 },
    contact: { phone: '+255-736-500100', website: 'https://www.asiliaafrica.com' },
    rating: 4.8,
  },
  // Zanzibar
  {
    id: 'zan-1',
    name: 'Stone Town',
    country: 'Zanzibar',
    type: 'Attraction',
    description: 'The old part of Zanzibar City, a UNESCO World Heritage Site.',
    longDescription: 'Stone Town is the cultural heart of Zanzibar. It is a city of prominent historical and artistic importance in East Africa. Its winding lanes present a mosaic of carved doorways, mosques, and stone buildings. It is a place to get lost in, exploring the shops, bazaars, and historic sites.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -6.166, lng: 39.199 },
    contact: { phone: 'N/A', website: 'https://whc.unesco.org/en/list/173' },
    rating: 4.7,
  },
  {
    id: 'zan-2',
    name: 'The Rock Restaurant',
    country: 'Zanzibar',
    type: 'Restaurant',
    description: 'A world-famous restaurant perched on a rock in the Indian Ocean.',
    longDescription: 'The Rock Restaurant is a truly unique dining destination. Situated on a rock in the middle of the Indian Ocean, it is accessible by foot during low tide and by boat during high tide. The restaurant specializes in fresh seafood and offers breathtaking views of the ocean and the coastline.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -6.223, lng: 39.510 },
    contact: { phone: '+255-776-591-360', website: 'https://www.rockrestaurantzanzibar.com' },
    rating: 4.6,
  },
  // Rwanda
  {
    id: 'rw-1',
    name: 'Volcanoes National Park',
    country: 'Rwanda',
    type: 'Attraction',
    description: 'A haven for the mountain gorilla and golden monkeys.',
    longDescription: 'Volcanoes National Park is situated in northwestern Rwanda and is home to the endangered mountain gorilla and a rich mosaic of montane ecosystems, which embrace evergreen and bamboo forest, open grassland, swamp and heath. It is named after the chain of dormant volcanoes making up the Virunga Massif.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.463, lng: 29.493 },
    contact: { phone: '+250-788-319-300', website: 'https://www.rdb.rw' },
    rating: 4.8,
  },
  {
    id: 'rw-2',
    name: 'The Retreat by Heaven',
    country: 'Rwanda',
    type: 'Hotel',
    description: 'A luxury boutique hotel in the heart of Kigali.',
    longDescription: 'The Retreat is a 20-room luxury boutique hotel created by the American owners of Heaven Restaurant. It offers a five-star experience with a focus on Rwandan culture, sustainability and wellness. The hotel features a solar-heated saltwater swimming pool, a full-service spa, and a farm-to-table restaurant.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    location: { lat: -1.957, lng: 30.060 },
    contact: { phone: '+250-788-305-825', website: 'https://www.heavenrwanda.com' },
    rating: 4.7,
  },
];
